# Generated by Django 4.1.1 on 2023-01-10 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SingleProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=200)),
                ("baths", models.IntegerField()),
                ("bedrooms", models.IntegerField()),
                ("city", models.CharField(max_length=200)),
                ("maintenance", models.BooleanField(blank=True, null=True)),
                ("price", models.IntegerField()),
                ("rented", models.BooleanField(blank=True, null=True)),
                ("type", models.CharField(max_length=200)),
                ("zip", models.CharField(max_length=10)),
                ("square_feet", models.FloatField()),
                ("pets", models.BooleanField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="realtor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
