# Generated by Django 4.1.1 on 2022-11-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="singleproperty",
            name="need_maintenace",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="singleproperty",
            name="year_built",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
