# Generated by Django 4.1.1 on 2022-09-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="phone_number",
            field=models.IntegerField(blank=True),
        ),
    ]
