# Generated by Django 4.1.1 on 2022-09-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_user", "0002_alter_appuser_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="phone_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
