# Generated by Django 4.1.1 on 2022-10-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_user", "0004_alter_appuser_options_appuser_date_joined_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name="appuser",
            name="last_name",
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
