# Generated by Django 4.1.1 on 2022-10-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_user", "0005_alter_appuser_first_name_alter_appuser_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appuser",
            name="date_of_birth",
        ),
        migrations.AddField(
            model_name="appuser",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="appuser",
            name="country",
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
