# Generated by Django 4.1.1 on 2022-10-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_user", "0006_remove_appuser_date_of_birth_appuser_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
